import { CurrentChatProvider } from "./(main)/_providers/current-chat-provider";
import { CurrentTabProvider } from "./(main)/_providers/current-tab-provider";
import { SearchProvider } from "./(main)/_providers/search-provider";
import { SettingsDrawerProvider } from "./(main)/_providers/settings-drawer-provider";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <SearchProvider>
      <CurrentTabProvider>
        <CurrentChatProvider>
          <SettingsDrawerProvider>{children}</SettingsDrawerProvider>
        </CurrentChatProvider>
      </CurrentTabProvider>
    </SearchProvider>
  );
}
