name: echo

services:
  redis:
    image: redis:7
    container_name: echo_redis
    restart: unless-stopped
    environment:
      - REDIS_PORT=6379
      - REDIS_USER=echo
      - REDIS_PASSWORD=echo
    ports:
      - "6379:6379"



