name: echo

services:
  postgres:
    image: postgres:15
    container_name: echo_postgres
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      start_period: 30s
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_DB=echo
      - POSTGRES_USER=echo
      - POSTGRES_PASSWORD=echo
    ports:
      - "5432:5432"

